# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

[default]
extend-ignore-identifiers-re = [
  "^(ba|pn|PN|UE)$",
  "^(CNA|ser)$",
  "^(ECT0|ECT1|HELO|htpt|PASE)$",
  "^[A-Za-z0-9_-]*(EDE|GOST)[A-Z0-9_-]*$",  # ciphers
  "^0x[0-9a-fA-F]+FUL$",  # unsigned long hex literals ending with 'F'
  "^(eyeballers|HELO_smtp|optin|passin|perfec|SMTP_HELO)$",
  "^(clen|req_clen|smtp_perform_helo|smtp_state_helo_resp|_stati64)$",
  "^Tru64$",
  "secur32",
  "proxys",  # this should be limited to tests/http/*. Short for secure proxy.
]

extend-ignore-re = [
  ".*spellchecker:disable-line",
]

[files]
extend-exclude = [
  ".github/scripts/codespell-ignore.txt",
  ".github/scripts/spellcheck.words",
  "docs/THANKS",
  "packages/*",
  "scripts/wcurl",
  "projects/Windows/tmpl/curl.vcxproj",
  "projects/Windows/tmpl/libcurl.vcxproj",
  "tests/data/test*",
]
