name: Linux

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
    - master
    - '*/ci'
  pull_request:
    branches:
    - master

jobs:
  autotools:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: hyper
          install:
          configure: --with-openssl --with-hyper=$HOME/hyper --enable-headers-api

    steps:
    - run: |
        sudo apt-get install libtool autoconf automake pkg-config
        sudo python3 -m pip install impacket
      name: install prereqs and impacket

    - run: (cd $HOME;
        git clone --depth=1 https://github.com/hyperium/hyper.git;
        curl https://sh.rustup.rs -sSf | sh -s -- -y;
        source $HOME/.cargo/env;
        rustup toolchain install nightly;)
      name: install rust

    - run: (cd $HOME/hyper;
        RUSTFLAGS="--cfg hyper_unstable_ffi" cargo +nightly rustc --features client,http1,http2,ffi -Z unstable-options --crate-type cdylib)
      name: 'install hyper'

    - uses: actions/checkout@v2

    - run: autoreconf -fi && LDFLAGS="-Wl,-rpath,$HOME/hyper/target/debug" ./configure --enable-warnings --enable-werror ${{ matrix.build.configure }} && make V=1
      name: 'configure and build'

    - run: make V=1 test-ci
      name: 'test'
      env:
        LD_LIBRARY_PATH: $HOME/hyper/target/debug:/usr/local/lib
        TFLAGS: "${{ matrix.build.tflags }}"
