name: Linux

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
    - master
    - '*/ci'
  pull_request:
    branches:
    - master

jobs:
  autotools:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: wolfssl (configured with --enable-all)
          install:
          wolfssl-configure: --enable-all
          curl-configure: --with-wolfssl=$HOME/wssl --enable-debug --enable-werror
        - name: wolfssl (configured with --enable-opensslextra)
          install:
          wolfssl-configure: --enable-opensslextra
          curl-configure: --with-wolfssl=$HOME/wssl --enable-debug --enable-werror

    steps:
    - run: |
        sudo apt-get install libtool autoconf automake pkg-config stunnel4
        sudo python3 -m pip install impacket
      name: install prereqs and impacket

    - run: |
        curl -LO https://github.com/wolfSSL/wolfssl/archive/v5.0.0-stable.tar.gz
        tar -xzf v5.0.0-stable.tar.gz
        cd wolfssl-5.0.0-stable
        ./autogen.sh
        ./configure --enable-tls13 ${{ matrix.build.wolfssl-configure }} --enable-harden --prefix=$HOME/wssl
        make && make install
      name: 'install wolfssl'

    - uses: actions/checkout@v2

    - run: autoreconf -fi && LDFLAGS="-Wl,-rpath,$HOME/wssl/lib" ./configure --enable-warnings --enable-werror --enable-headers-api ${{ matrix.build.curl-configure }} && make V=1
      name: 'configure and build'

    - run: make V=1 test-ci
      name: 'test'
      env:
        TFLAGS: "${{ matrix.build.tflags }}"
